//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeega.Web.Localization.Nav {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainNavRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainNavRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zeega.Web.Localization.Nav.MainNavRes", typeof(MainNavRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Games.
        /// </summary>
        public static string AllGames {
            get {
                return ResourceManager.GetString("AllGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Games.
        /// </summary>
        public static string BrowseGames {
            get {
                return ResourceManager.GetString("BrowseGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently playing.
        /// </summary>
        public static string CurrentlyPlaying {
            get {
                return ResourceManager.GetString("CurrentlyPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured.
        /// </summary>
        public static string Featured {
            get {
                return ResourceManager.GetString("Featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most popular all time.
        /// </summary>
        public static string MostPopularAllTime {
            get {
                return ResourceManager.GetString("MostPopularAllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most popular this month.
        /// </summary>
        public static string MostPopularThisMonth {
            get {
                return ResourceManager.GetString("MostPopularThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most popular this week.
        /// </summary>
        public static string MostPopularThisWeek {
            get {
                return ResourceManager.GetString("MostPopularThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot new games.
        /// </summary>
        public static string NewGames {
            get {
                return ResourceManager.GetString("NewGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play history.
        /// </summary>
        public static string PlayHistory {
            get {
                return ResourceManager.GetString("PlayHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play later.
        /// </summary>
        public static string PlayLater {
            get {
                return ResourceManager.GetString("PlayLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Games and more.
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top rated.
        /// </summary>
        public static string TopRated {
            get {
                return ResourceManager.GetString("TopRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to play.
        /// </summary>
        public static string WhatToPlay {
            get {
                return ResourceManager.GetString("WhatToPlay", resourceCulture);
            }
        }
    }
}
